// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ASWCpp
double ASWCpp(IntegerVector C, NumericVector dist, int N, int k);
RcppExport SEXP _EfficientOASW_ASWCpp(SEXP CSEXP, SEXP distSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(ASWCpp(C, dist, N, k));
    return rcpp_result_gen;
END_RCPP
}
// effOSilCpp
List effOSilCpp(NumericVector dist, IntegerVector iC, int N, int k);
RcppExport SEXP _EfficientOASW_effOSilCpp(SEXP distSEXP, SEXP iCSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iC(iCSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(effOSilCpp(dist, iC, N, k));
    return rcpp_result_gen;
END_RCPP
}
// OSilCpp
List OSilCpp(NumericVector dist, IntegerVector iC, int N, int k);
RcppExport SEXP _EfficientOASW_OSilCpp(SEXP distSEXP, SEXP iCSEXP, SEXP NSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iC(iCSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(OSilCpp(dist, iC, N, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EfficientOASW_ASWCpp", (DL_FUNC) &_EfficientOASW_ASWCpp, 4},
    {"_EfficientOASW_effOSilCpp", (DL_FUNC) &_EfficientOASW_effOSilCpp, 4},
    {"_EfficientOASW_OSilCpp", (DL_FUNC) &_EfficientOASW_OSilCpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_EfficientOASW(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
