# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
.ASWCpp <- function(C, dist, N, k) {
    .Call(`_EfficientOASW_ASWCpp`, C, dist, N, k)
}

#' @export
.effOSilCpp <- function(dist, iC, N, k) {
    .Call(`_EfficientOASW_effOSilCpp`, dist, iC, N, k)
}

#' @export
.OSilCpp <- function(dist, iC, N, k) {
    .Call(`_EfficientOASW_OSilCpp`, dist, iC, N, k)
}

