# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ASWCpp <- function(C, dist, N, k) {
    .Call(`_ASW_ASWCpp`, C, dist, N, k)
}

.subDistCpp <- function(dist, idx, diag, upper, N, n) {
    .Call(`_ASW_subDistCpp`, dist, idx, diag, upper, N, n)
}

.SWCpp <- function(C, dist, N, k) {
    .Call(`_ASW_SWCpp`, C, dist, N, k)
}

.effOSilCpp <- function(dist, iC, N, k) {
    .Call(`_ASW_effOSilCpp`, dist, iC, N, k)
}

.OSilCpp <- function(dist, iC, N, k) {
    .Call(`_ASW_OSilCpp`, dist, iC, N, k)
}

.scalOSil_PC <- function(dist, iC, N, k) {
    .Call(`_ASW_scalOSil_PC_Step`, dist, iC, N, k)
}

.scalOSil_C <- function(dist, k, PC_result, idxPC, idxC, n1, n2, N) {
    .Call(`_ASW_scalOSil_C_Step`, dist, k, PC_result, idxPC, idxC, n1, n2, N)
}

.FOSil_PC <- function(dist, iC, N, k) {
    .Call(`_ASW_FOSil_PC_Step`, dist, iC, N, k)
}

.FOSil_C <- function(dist, distPC, k, PC_result, idxPC, idxC, n1, n2, N) {
    .Call(`_ASW_FOSil_C_Step`, dist, distPC, k, PC_result, idxPC, idxC, n1, n2, N)
}

.PAMSilCpp <- function(dist, C, medoids, N, k) {
    .Call(`_ASW_PAMSilCpp`, dist, C, medoids, N, k)
}

